// Binary message types (net channel)
export const BIN = { SNAPSHOT: 0x01, INPUT: 0x02 };

// Flag bits in snapshot player record
export const FLAG = {
  ALIVE: 1 << 0,
  VENTING: 1 << 1,
  MOVING: 1 << 2,
  SPRINTING: 1 << 3,
  IN_MINIGAME: 1 << 4,
  GHOST: 1 << 5,
};

// Action bits in input record
export const ACT = {
  INTERACT: 1 << 0,
  KILL: 1 << 1,
  REPORT: 1 << 2,
  VENT: 1 << 3,
  SPRINT: 1 << 4,
  MINIGAME: 1 << 5,
};

// JSON event types (evt channel). Shape: { t: TYPE, ...payload }
export const MSG = {
  // mesh bookkeeping
  HELLO: 'HELLO',
  ROSTER: 'ROSTER',
  HOST_CLAIM: 'HOST_CLAIM',
  PING: 'PING',
  PONG: 'PONG',
  // client -> host
  JOIN: 'JOIN',
  SET_NAME: 'SET_NAME',
  SET_COLOR: 'SET_COLOR',
  READY: 'READY',
  START_GAME: 'START_GAME',
  SET_SETTINGS: 'SET_SETTINGS',
  TASK_COMPLETE: 'TASK_COMPLETE',
  KILL_ATTEMPT: 'KILL_ATTEMPT',
  REPORT_BODY: 'REPORT_BODY',
  EMERGENCY_MEETING: 'EMERGENCY_MEETING',
  VOTE: 'VOTE',
  SABOTAGE_REQUEST: 'SABOTAGE_REQUEST',
  SABOTAGE_FIX: 'SABOTAGE_FIX',
  VENT_ENTER: 'VENT_ENTER',
  VENT_MOVE: 'VENT_MOVE',
  VENT_EXIT: 'VENT_EXIT',
  MINIGAME_STATE: 'MINIGAME_STATE',
  CHAT: 'CHAT',
  // host -> clients
  LOBBY_STATE: 'LOBBY_STATE',
  PHASE: 'PHASE',
  PLAYER_LEFT: 'PLAYER_LEFT',
  ROLE_ASSIGN: 'ROLE_ASSIGN',
  GAME_START: 'GAME_START',
  KILL_CONFIRMED: 'KILL_CONFIRMED',
  MEETING_START: 'MEETING_START',
  MEETING_PHASE: 'MEETING_PHASE',
  VOTE_CAST: 'VOTE_CAST',
  VOTE_RESULT: 'VOTE_RESULT',
  TASK_PROGRESS: 'TASK_PROGRESS',
  TASK_ACK: 'TASK_ACK',
  SABOTAGE_START: 'SABOTAGE_START',
  SABOTAGE_UPDATE: 'SABOTAGE_UPDATE',
  SABOTAGE_END: 'SABOTAGE_END',
  GAME_END: 'GAME_END',
  DOOR_STATE: 'DOOR_STATE',
  TELEPORT: 'TELEPORT',
  VENT_STATE: 'VENT_STATE',
  FLARE: 'FLARE',
  KILL_COOLDOWN: 'KILL_COOLDOWN',
  STATION_GLOW: 'STATION_GLOW',
  ERROR: 'ERROR',
};
