// LEVEL 1 — THE FOUNDRY (vertical). Industrial smelting facility on three stacked levels
// around a central molten shaft. Sightline gimmick: verticality through grating catwalks.
const H = Math.PI / 2;

export default {
  id: 'foundry',
  name: 'The Foundry',
  palette: { primary: 0x3a4a5a, accent: 0xff7a3d, floor: 0x2a2a30, wall: 0x35404a, ceiling: 0x1f2328, emissive: 0xffaa44, surface: 'metal', floorTex: 'metal', wallTex: 'wall' },
  background: 0x0a0604,
  spawn: [0, 0, 29],
  spawnRadius: 3,
  meetingTable: [0, 0, 25],
  rooms: [
    { id: 'hall', name: 'Smelting Floor', pos: [0, 0, 0], size: [36, 14, 36], reverb: 'large-metal', floorTex: 'metal' },
    { id: 'reactor', name: 'Reactor Core', pos: [-27, 0, 0], size: [16, 8, 16], reverb: 'large-metal', wallColor: 0x2e3a4a, floorColor: 0x23262b },
    { id: 'ore', name: 'Ore Processing', pos: [27, 0, -4], size: [16, 6, 18], reverb: 'large-metal', floorTex: 'concrete', floorColor: 0x3a3632 },
    { id: 'coolant', name: 'Coolant Bay', pos: [0, 0, -26], size: [18, 6, 14], reverb: 'large-metal', wallColor: 0x2c3e4e, floorColor: 0x22303a },
    { id: 'dock', name: 'Loading Dock', pos: [0, 0, 26], size: [20, 5, 14], reverb: 'small-room', floorTex: 'concrete', floorColor: 0x3b3a38 },
    { id: 'storage', name: 'Storage', pos: [-24, 0, 24], size: [12, 5, 10], reverb: 'small-room' },
    // Control room: a glass box on the upper platform inside the hall
    { id: 'control', name: 'Control Room', pos: [0, 9.5, -13], size: [12, 3.5, 6], glass: true, reverb: 'small-room', floorColor: 0x353a40, openings: { s: [{ a: -1.5, b: 1.5, h: 3 }] } },
  ],
  corridors: [
    { from: 'hall', to: 'reactor', width: 3.5, height: 3.6 },
    { from: 'hall', to: 'ore', width: 3.5, height: 3.6 },
    { from: 'hall', to: 'coolant', width: 3.5, height: 3.6 },
    { from: 'hall', to: 'dock', width: 4, height: 3.6 },
    { from: 'dock', to: 'storage', width: 3, height: 3.2 },
    { from: 'reactor', to: 'storage', width: 3, height: 3.2 },
  ],
  // Catwalk ring at y=5 around the shaft, landings, and an upper platform to the control room
  platforms: [
    { pos: [0, 5, -9], size: [21, 0.3, 3], grating: true, rails: ['s'] },
    { pos: [0, 5, 9], size: [21, 0.3, 3], grating: true, rails: ['n'] },
    { pos: [-9, 5, 0], size: [3, 0.3, 15], grating: true, rails: ['e'] },
    { pos: [9, 5, 0], size: [3, 0.3, 15], grating: true, rails: ['w'] },
    { pos: [-12, 5, 9], size: [3, 0.3, 3], grating: true, rails: ['n', 'w'] },
    { pos: [12, 5, -9], size: [3, 0.3, 3], grating: true, rails: ['s', 'e'] },
    { pos: [0, 9.47, -8.5], size: [10, 0.3, 3], grating: true, rails: ['s'] },
  ],
  stairs: [
    { from: [-12, 0, 17.5], to: [-12, 5, 10.5], width: 2.5 },
    { from: [12, 0, -17.5], to: [12, 5, -10.5], width: 2.5 },
    { from: [10, 5, -9], to: [5, 9.47, -9], width: 2.4 },
  ],
  walls: [],
  props: [
    { type: 'furnace', pos: [-12, 0, -13], rot: 0.4 },
    { type: 'furnace', pos: [12, 0, 13], rot: Math.PI + 0.3 },
    { type: 'pipeCluster', pos: [-17.4, 0, -10], rot: H },
    { type: 'pipeCluster', pos: [17.4, 0, 8], rot: -H },
    { type: 'pipeCluster', pos: [-17.4, 0, 2], rot: H },
    { type: 'pipeCluster', pos: [-34.4, 0, 0], rot: H },
    { type: 'pipeCluster', pos: [-20, 0, -7.4], rot: 0 },
    { type: 'pipeCluster', pos: [-4, 0, -32.4], rot: 0 },
    { type: 'oreCart', pos: [24, 0, -9], rot: 0.2 },
    { type: 'oreCart', pos: [30, 0, 1], rot: -1.2 },
    { type: 'oreCart', pos: [-5, 0, 14], rot: 0.9 },
    { type: 'crateStack', pos: [-6, 0, 29], rot: 0.2 },
    { type: 'crateStack', pos: [6, 0, 30], rot: -0.4 },
    { type: 'crate', pos: [-8, 0, 21], rot: 0.5 },
    { type: 'crate', pos: [-26, 0, 27], rot: 0.1 },
    { type: 'crateStack', pos: [-21, 0, 20], rot: 1.1 },
    { type: 'barrel', pos: [-28, 0, 21] },
    { type: 'barrel', pos: [-28.9, 0, 22.2] },
    { type: 'barrel', pos: [8, 0, 21] },
    { type: 'barrel', pos: [-15, 0, 15] },
    { type: 'tank', pos: [-6, 0, -30], scale: 0.9 },
    { type: 'tank', pos: [6, 0, -30], scale: 0.9 },
    { type: 'tank', pos: [-22, 0, -4], scale: 1.2 },
    { type: 'server', pos: [-4.5, 9.5, -15.5] },
    { type: 'server', pos: [4.5, 9.5, -15.5] },
    { type: 'pillar', pos: [-15, 0, -15] },
    { type: 'pillar', pos: [15, 0, -15] },
    { type: 'pillar', pos: [-15, 0, 15] },
    { type: 'pillar', pos: [15, 0, 15] },
    { type: 'lamp', pos: [-13, 0, 5] },
    { type: 'lamp', pos: [13, 0, -5] },
    { type: 'locker', pos: [8, 0, 32.3], rot: Math.PI },
    { type: 'bench', pos: [-3, 0, 31.5] },
  ],
  vents: [
    { id: 'v1', pos: [-26, 0, -5], connects: ['v2', 'v5'] },
    { id: 'v2', pos: [-5, 0, -24], connects: ['v1', 'v3'] },
    { id: 'v3', pos: [26, 0, 2], connects: ['v2', 'v6'] },
    { id: 'v4', pos: [-15, 0, 13], connects: ['v5', 'v6'] },
    { id: 'v5', pos: [-24, 0, 20.5], connects: ['v1', 'v4'] },
    { id: 'v6', pos: [7, 0, 24], connects: ['v3', 'v4'] },
  ],
  taskStations: [
    { id: 'ts_react_purge', pos: [-34.4, 0, -5], rot: H, minigame: 'coolantPurge', label: 'Purge' },
    { id: 'ts_react_cal', pos: [-34.4, 0, 5], rot: H, minigame: 'reactorCalibrate', label: 'Calibrate' },
    { id: 'ts_cool_press', pos: [0, 0, -32.4], rot: 0, minigame: 'airlockPressurize', label: 'Pressure' },
    { id: 'ts_cool_spec', pos: [-8.4, 0, -26], rot: H, minigame: 'spectrometer', label: 'Spectro' },
    { id: 'ts_hall_wire', pos: [-17.4, 0, -5], rot: H, minigame: 'wireSplice', label: 'Wiring' },
    { id: 'ts_hall_scan', pos: [17.4, 0, -10], rot: -H, minigame: 'identScan', label: 'ID Scan', visual: true },
    { id: 'ts_ore_sort', pos: [34.4, 0, -4], rot: -H, minigame: 'cargoSort', label: 'Sort Ore' },
    { id: 'ts_ore_crush', pos: [27, 0, -12.4], rot: 0, minigame: 'debrisClear', label: 'Crusher' },
    { id: 'ts_ctrl_upload', pos: [-1, 9.5, -15.4], rot: 0, minigame: 'dataUpload', label: 'Upload', downloadAt: 'ts_dock_download' },
    { id: 'ts_dock_download', pos: [9.4, 0, 27], rot: -H, minigame: 'dataUpload', label: 'Download', downloadOnly: true },
    { id: 'ts_store_inv', pos: [-24, 0, 28.4], rot: Math.PI, minigame: 'seedCatalogue', label: 'Inventory' },
    { id: 'ts_store_wire', pos: [-29.4, 0, 26], rot: H, minigame: 'wireSplice', label: 'Wiring' },
    { id: 'ts_dock_sort', pos: [-9.4, 0, 29], rot: H, minigame: 'cargoSort', label: 'Manifest' },
    { id: 'ts_walk_valves', pos: [-5, 5, -9.9], rot: 0, minigame: 'coolantPurge', label: 'Valves' },
    { id: 'ts_walk_spec', pos: [-9.9, 5, 3], rot: H, minigame: 'spectrometer', label: 'Gauges' },
  ],
  sabotageStations: [
    { id: 'fix_lights', type: 'lights', pos: [-17.4, 0, 8], rot: H, label: 'Electrical' },
    { id: 'fix_comms', type: 'comms', pos: [3.5, 9.5, -15.4], rot: 0, label: 'Comms' },
    { id: 'fix_react_a', type: 'reactor', index: 0, pos: [-27, 0, -7.4], rot: 0, label: 'Reactor A' },
    { id: 'fix_react_b', type: 'reactor', index: 1, pos: [-27, 0, 7.4], rot: Math.PI, label: 'Reactor B' },
    { id: 'fix_o2_a', type: 'o2', index: 0, pos: [7, 0, -32.4], rot: 0, label: 'O2 Filter' },
    { id: 'fix_o2_b', type: 'o2', index: 1, pos: [34.4, 0, -10], rot: -H, label: 'O2 Filter' },
  ],
  doors: [
    { id: 'd_reactor', room: 'reactor', pos: [-18.5, 0, 0], rot: H, width: 3.5, height: 3.6 },
    { id: 'd_ore', room: 'ore', pos: [18.5, 0, -4], rot: H, width: 3.5, height: 3.6 },
    { id: 'd_coolant', room: 'coolant', pos: [0, 0, -18.5], rot: 0, width: 3.5, height: 3.6 },
    { id: 'd_dock', room: 'dock', pos: [0, 0, 18.5], rot: 0, width: 4, height: 3.6 },
    { id: 'd_storage', room: 'storage', pos: [-14, 0, 24], rot: H, width: 3, height: 3.2 },
  ],
  lights: [
    { type: 'ambient', color: 0x664433, intensity: 0.22 },
    { type: 'point', pos: [0, 4, 0], color: 0xff8833, intensity: 160, range: 44, flare: true, castShadow: true },
    { type: 'point', pos: [-14, 12, -14], color: 0xff9944, intensity: 40, range: 24 },
    { type: 'point', pos: [14, 12, -14], color: 0xff9944, intensity: 40, range: 24 },
    { type: 'point', pos: [-14, 12, 14], color: 0xff9944, intensity: 40, range: 24 },
    { type: 'point', pos: [14, 12, 14], color: 0xff9944, intensity: 40, range: 24 },
    { type: 'point', pos: [0, 12.6, -13], color: 0xffffff, intensity: 45, range: 14 },
    { type: 'point', pos: [-27, 7, 0], color: 0x66aaff, intensity: 90, range: 24 },
    { type: 'point', pos: [0, 5.5, -26], color: 0x66ccff, intensity: 50, range: 20 },
    { type: 'point', pos: [27, 5.5, -4], color: 0xffaa66, intensity: 70, range: 24 },
    { type: 'point', pos: [0, 4.6, 26], color: 0xffffff, intensity: 60, range: 22 },
    { type: 'point', pos: [-24, 4.6, 24], color: 0xffcc88, intensity: 30, range: 16 },
  ],
  special: [{ type: 'lavaShaft', pos: [0, 0, 0], radius: 4 }],
  ambience: { reverb: 'large-metal', bedTrack: 'industrial', flares: true },
};
