// The lobby is itself a level: a small dropship. Players walk around and talk while the host configures.
export default {
  id: 'lobby',
  name: 'Dropship',
  palette: { primary: 0x3b4652, accent: 0x7fb2ff, floor: 0x2c3138, wall: 0x3b4652, ceiling: 0x2a3038, emissive: 0x7fb2ff, surface: 'metal' },
  fogColor: 0x353c46,
  background: 0x05070c,
  spawn: [0, 0, 2],
  spawnRadius: 3,
  meetingTable: [0, 0, -3],
  rooms: [
    { id: 'bay', name: 'Dropship Bay', pos: [0, 0, 0], size: [18, 5, 14], reverb: 'small-room' },
    { id: 'cockpit', name: 'Cockpit', pos: [0, 0, -11], size: [8, 4, 6], glass: true, reverb: 'small-room' },
  ],
  corridors: [{ from: 'bay', to: 'cockpit', width: 3, height: 3.2 }],
  props: [
    { type: 'crateStack', pos: [-7, 0, 5], rot: 0.3 },
    { type: 'crate', pos: [7, 0, 5.5], rot: -0.2 },
    { type: 'barrel', pos: [7.8, 0, 3.5] },
    { type: 'locker', pos: [-8.3, 0, -3], rot: Math.PI / 2 },
    { type: 'locker', pos: [8.3, 0, -3], rot: -Math.PI / 2 },
    { type: 'server', pos: [-3, 0, -13.5] },
    { type: 'server', pos: [3, 0, -13.5] },
    { type: 'bench', pos: [-5, 0, -5.5] },
    { type: 'bench', pos: [5, 0, -5.5] },
    { type: 'plant', pos: [-8, 0, 6] },
    { type: 'plant', pos: [8, 0, -6] },
  ],
  vents: [],
  taskStations: [],
  sabotageStations: [],
  doors: [],
  lights: [
    { type: 'ambient', color: 0x8aa0c0, intensity: 0.35 },
    { type: 'hemi', color: 0x9fb8ff, ground: 0x1a1f2a, intensity: 0.5 },
    { type: 'point', pos: [0, 4.5, 2], color: 0xdfe8ff, intensity: 60, range: 22 },
    { type: 'point', pos: [-6, 4.5, -4], color: 0x7fb2ff, intensity: 30, range: 16 },
    { type: 'point', pos: [6, 4.5, -4], color: 0x7fb2ff, intensity: 30, range: 16 },
    { type: 'point', pos: [0, 3.5, -11], color: 0xffffff, intensity: 30, range: 12 },
  ],
  special: [],
  ambience: { reverb: 'small-room', bedTrack: 'ambient-space' },
};
